# github workflow to build and test the project

name : Build and Test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses : actions/checkout@v2

            - name : set up nodeV20
              uses : actions/setup-node@v2
              with:
                  node-version: '20.11.1'
            
            - name : install dependencies
              run: npm install

            - name : run build
              run: npm run build  

# 2nd job run shell scripts
    custom-script:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - name: Run a one-line script
              run: |
                 chmod +x t1.sh # Ensure the script is executable
                 ./t1.sh
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release
                